[[questions]]
id = "8bd8d8bc-e61e-48c7-ba78-0c89339e5995"
type = "MultipleChoice"
prompt.prompt = "کدام عبارت بهتر توضیح می‌دهد اگر یک متغیر `x` «غیرقابل‌تغییر» (immutable) باشد یعنی چه؟"
answer.answer = "`x` بعد از اینکه مقداردهی شد دیگر نمی‌تواند تغییر کند."
prompt.distractors = [
  "`x` در ناحیهٔ غیرقابل‌تغییر حافظه ذخیره می‌شود.",
  "بعد از تعریف شدن، `x` حداکثر یک بار می‌تواند تغییر کند.",
  "نمی‌توانید یک ارجاع (reference) به `x` ایجاد کنید."
]
context = """
Immutable یعنی «غیرقابل‌تغییر» (not mutable) یا غیرقابل تغییر.
"""

[[questions]]
id = "dcf53c67-b3c9-4c54-8da0-90749cc669e8"
type = "ShortAnswer"
prompt.prompt = "برای اینکه نشان دهیم یک متغیر قابل تغییر (mutate) است، بعد از `let` از چه کلمهٔ کلیدی استفاده می‌شود؟"
answer.answer = "mut"
context = """
مثلاً می‌توانید یک متغیر قابل تغییر `x` را با نوشتن این کد بسازید: `let mut x = 1`.
"""

[[questions]]
id = "77f9f143-45a6-4f08-bd87-72bc50c00693"
type = "Tracing"
prompt.program = """
fn main() {
  let x = 1;
  println!("{x}");
  x += 1;
  println!("{x}");
}
"""
answer.doesCompile = false
answer.lineNumber = 4
context = """
این یک خطای کامپایلر است چون خط ۴ سعی می‌کند `x` را تغییر دهد، در حالی که `x` با `mut` مشخص نشده است.
"""
