[[questions]]
id = "a48e524e-852c-400c-ae68-5c76a6761596"
type = "MultipleChoice"
prompt.prompt = "کدام‌یک از عبارت‌های زیر درباره تفاوت استفاده از `let` و `const` برای اعلان یک متغیر درست است؟"
answer.answer = "`const` را می‌توان در سطح سراسری (global) استفاده کرد، اما `let` فقط درون یک تابع قابل استفاده است."
prompt.distractors = [
  "این‌ها فقط دو نوع سینتکس متفاوت برای اعلان متغیر هستند با همان معنا (semantics)",
  "کامپایلر خطا می‌دهد اگر نام یک متغیر `const` از الگوی `UPPER_SNAKE_CASE` استفاده نکند",
  "یک `const` فقط می‌تواند به یک مقدار (literal) اختصاص داده شود، نه به یک عبارتِ شامل محاسبه"
]

[[questions]]
id = "d209784f-cc52-4451-8049-ad204e89d587"
type = "Tracing"
prompt.program = """
const TWO: u32 = 1 + 1;
fn main() {
  println!("{TWO}");
}
"""
answer.doesCompile = true
answer.stdout = "2"
context = """
متغیرهای `const` اجازه دارند خارج از یک تابع تعریف شوند و همچنین می‌توانند انواع محدودی از محاسبات را انجام دهند.
"""
