[[questions]]
id = "d172fc53-0220-4ff4-83c9-9c0a6834dd8e"
type = "MultipleChoice"
prompt.prompt = "۱ + ۱ چند می‌شود؟ (روی یک پاسخ اشتباه کلیک کنید.)"
answer.answer = "۲"
prompt.distractors = [ "۰", "-۹۹۹", "۱۱" ]
context = """
See *Principia Mathematica* for an explanation of this fact.
"""
